// Generated by CoffeeScript 1.7.1
(function() {
  window.onload = function() {
    return document.getElementById('to').onclick = function() {
      var txt, yaml_str;
      yaml_str = document.getElementById('yaml').value;
      txt = SurfacesYaml.yaml_to_txt(yaml_str);
      return document.getElementById('txt').value = txt;
    };
  };

}).call(this);
