// Generated by CoffeeScript 1.7.1
(function() {
  window.onload = function() {
    document.getElementById('to').onclick = function() {
      var e, txt, yaml_str;
      yaml_str = document.getElementById('yaml').value;
      try {
        txt = SurfacesYaml.yaml_to_txt(yaml_str);
      } catch (_error) {
        e = _error;
        alert(e);
      }
      return document.getElementById('txt').value = txt;
    };
    return document.getElementById('set_example').onclick = function() {
      var yaml_str;
      yaml_str = ajax.gets('examples/surfaces.yaml');
      return document.getElementById('yaml').value = yaml_str;
    };
  };

}).call(this);
